name: smartconsultor
description: smart consultor project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter    
  # Service locator
  get_it: ^7.6.4
  # Bloc for state management
  flutter_bloc: ^8.1.3
  # Value equality
  equatable: ^2.0.5
  # Functional programing thingies 
  dartz: ^0.10.1
  # Remote API
  connectivity_plus: ^5.0.2
  http: 
  # Local cache
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  hive_generator: ^2.0.1  
  responsive_framework: ^1.1.1 
  flutter_dotenv: ^5.1.0
  parse_server_sdk: 
  google_fonts: 
  url_launcher: ^6.2.3
  universal_platform: ^1.0.0+1
  flutter_secure_storage: ^9.0.0
  universal_io: ^2.2.2
  logger: ^2.0.2+1
  flex_color_scheme: ^7.3.1
  flutter_svg: ^2.0.9
  
dev_dependencies: 
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mocktail: ^1.0.2  
  bloc_test: ^9.1.5
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - development.env
    - production.env
    - images/ 

    
    